### ISSUE TITLE
prepare for hacktoberfest

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/rosetta#1]
@artileda silahkan wkkw

- [x] create CONTRIBUTING.md
- [x] create pull request template
- [x] put hacktoberfest tag
- [x] create issues on what language should be written on
- [x] put a few hacktoberfest guides on readme such as:
  - https://twitter.com/sudo_navendu/status/1437456596473303042
  - https://www.digitalocean.com/community/tutorials/hacktoberfest-contributor-s-guide-how-to-find-and-contribute-to-open-source-projects

additional nitpick: masukin link saweria teknum ke FUNDING.yml

**Comment by artileda** [comment]
Affirmative, AFK rn ntar tak tambahin
